USER_ROLE_SUPER_USER = 1
USER_ROLE_GUEST = 2



USER_ROLES = (
    (USER_ROLE_SUPER_USER, 'super admin'),
    (USER_ROLE_GUEST, 'guest'),
)

JOURNAL_TYPE_BULLET =  1
JOURNAL_TYPE_FOOD =  2
JOURNAL_TYPE_TRAVEL =  3
JOURNAL_TYPE_SPORT =  4

JOURNAL_TYPES = (
    (JOURNAL_TYPE_BULLET, 'bullet'),
    (JOURNAL_TYPE_FOOD, 'food'),
    (JOURNAL_TYPE_TRAVEL, 'travel'),
    (JOURNAL_TYPE_SPORT, 'sport'),
)