# Generated by Django 3.1.7 on 2021-03-20 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookJournalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Book name')),
                ('price', models.IntegerField(verbose_name='Book price')),
                ('description', models.TextField(verbose_name='Book description')),
                ('created_at', models.DateField(verbose_name='Book creation date')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookjournalbase.bookjournalbase')),
                ('num_pages', models.IntegerField(verbose_name='Number of pages')),
                ('genre', models.CharField(max_length=255, verbose_name='Book genre')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
            bases=('bookjournalbase.bookjournalbase',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookjournalbase.bookjournalbase')),
                ('role', models.SmallIntegerField(choices=[(1, 'bullet'), (2, 'food'), (3, 'travel'), (4, 'sport')], default=3)),
                ('publisher', models.CharField(max_length=500, verbose_name='Book publisher')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
            bases=('bookjournalbase.bookjournalbase',),
        ),
    ]
